### PR TITLE
fix upload extention

### PR DESCRIPTION
**Pull request by VladislavNikolaev**
Some properties was not visible in gradle file, fixed it by adding "def" keyword.

### CODE REVIEW

**Comment by devindi** [comment]
Hello! Thx for your PR but could you provide example that shows the problem.
Also there are recommendation to avoid using `def` and type http://groovy-lang.org/style-guide.html#_def_and_type

**Comment by VladislavNikolaev** [comment]
Hi @devindi , when i open sample project in android studio gradle shows me an error:

> Error:(56, 0) No such property: comment for class: com.devindi.gradle.diawi.dsl.DiawiUploadExtension_Decorated

[See screenshot](https://i.imgur.com/2wG2niY.png)

So i've decided to remove "comment" property, and after that i've got another one:

> Error:(56, 0) No such property: password for class: com.devindi.gradle.diawi.dsl.DiawiUploadExtension_Decorated

I have made some investigations and at last there was only two properties when i could sync gradle successfully it was: "token" and "standardOutput".

After that i've checked and compared your code with other plugins and decided that the only difference is "def" keywords in extention file. So after that i have added this keywords and i've synced gradle successfully with all properties.

I am using Android Studio 3.0.1

**Comment by devindi** [comment]
Make sure that you are using latest version (1.1) of plugin

`buildscript {
    repositories{
        jcenter()
    }
    dependencies{
        classpath 'com.devindi:diawi-upload:1.1'
    }
}`

It looks like that you are using plugin v1.0 which supports only "token" and "standardOutput" properties.

**Comment by VladislavNikolaev** [comment]
Yes, you are right, i have copy pasted classpath from Readme file. It's my fault. :)

Closing PR.

**Comment by devindi** [comment]
Great! I'll update readme

**Pull request closed without merging**
